package database.dao;

import database.model.TskToken;
import database.model.TskTokenCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TskTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsk_token
     *
     * @mbggenerated
     */
    int countByExample(TskTokenCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsk_token
     *
     * @mbggenerated
     */
    int deleteByExample(TskTokenCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsk_token
     *
     * @mbggenerated
     */
    int insert(TskToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsk_token
     *
     * @mbggenerated
     */
    int insertSelective(TskToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsk_token
     *
     * @mbggenerated
     */
    List<TskToken> selectByExample(TskTokenCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsk_token
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TskToken record, @Param("example") TskTokenCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsk_token
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TskToken record, @Param("example") TskTokenCriteria example);
}