package service;

import java.io.Serializable;
import java.util.Date;

public class TokenModel implements Serializable {

    public TokenModel() {
    }

    public TokenModel(String token, Date datetime) {
        this.token = token;
        this.datetime = datetime;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_token.token
     *
     * @mbggenerated
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_token.dateTime
     *
     * @mbggenerated
     */
    private Date datetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table remote_token
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_token.token
     *
     * @return the value of remote_token.token
     *
     * @mbggenerated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_token.token
     *
     * @param token the value for remote_token.token
     *
     * @mbggenerated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_token.dateTime
     *
     * @return the value of remote_token.dateTime
     *
     * @mbggenerated
     */
    public Date getDatetime() {
        return datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_token.dateTime
     *
     * @param datetime the value for remote_token.dateTime
     *
     * @mbggenerated
     */
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }

    @Override
    public String toString() {
        return "TokenModel{" +
                "token='" + token + '\'' +
                ", datetime=" + datetime +
                '}';
    }
}