package com.hsnn.datafetch.database.model;

import java.io.Serializable;
import java.util.Date;

public class TskToken implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the com.hsnn.datafetch.database column tsk_token.token
     *
     * @mbggenerated
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the com.hsnn.datafetch.database column tsk_token.dateTime
     *
     * @mbggenerated
     */
    private Date datetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the com.hsnn.datafetch.database table tsk_token
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the com.hsnn.datafetch.database column tsk_token.token
     *
     * @return the value of tsk_token.token
     *
     * @mbggenerated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the com.hsnn.datafetch.database column tsk_token.token
     *
     * @param token the value for tsk_token.token
     *
     * @mbggenerated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the com.hsnn.datafetch.database column tsk_token.dateTime
     *
     * @return the value of tsk_token.dateTime
     *
     * @mbggenerated
     */
    public Date getDatetime() {
        return datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the com.hsnn.datafetch.database column tsk_token.dateTime
     *
     * @param datetime the value for tsk_token.dateTime
     *
     * @mbggenerated
     */
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }

    @Override
    public String toString() {
        return "TskToken{" +
                "token='" + token + '\'' +
                ", datetime=" + datetime +
                '}';
    }
}